apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-app-user
  namespace: sample-app
  labels:
    app: sample-app
    tier: user
spec:
  to:
    kind: Service
    name: sample-app-user
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-app-admin
  namespace: sample-app
  labels:
    app: sample-app
    tier: admin
spec:
  host: admin-sample-app.apps.your-cluster.com  # Update with your cluster domain
  to:
    kind: Service
    name: sample-app-admin
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
